### ISSUE TITLE
tries to fetch url with tramp(?)

### ISSUE THREAD

**Issue by unhammer** [Wilfred/suggest.el#32]
Try putting an url in the input/output (as string) and pressing `C-c C-c`:

![suggest-url](https://user-images.githubusercontent.com/56868/30518791-a223b532-9b87-11e7-9aa9-76c4b2c1c871.png)

This seems like a bug :)

```
;; Version: 0.4
;; Package-Version: 0.4
```

**Comment by Wilfred** [comment]
Yep, suggest.el definitely shouldn't be making network connections!

**Comment by Wilfred** [comment]
This was a fun one to debug. It was trying to evaluate the following:

```emacs-lisp
(f-entries (expand-file-name "http://example.com" t))
```

This is because the path is:

```emacs-lisp
ELISP> (expand-file-name "http://example.com" t)
#("/scp:http:/example.com" 1 4
  (tramp-default t))
```
