### ISSUE TITLE
suggest--permutations ;; TODO: this would be a good match for dash.el.

### ISSUE THREAD

**Issue by Fuco1** [Wilfred/suggest.el#38]
FYI it has been done already :)

https://github.com/magnars/dash.el/pull/203

```elisp
(-permutations '(1 2 3))

((1 2 3)
 (1 3 2)
 (2 1 3)
 (2 3 1)
 (3 1 2)
 (3 2 1))
```

**Comment by Wilfred** [comment]
Filed https://github.com/magnars/dash.el/issues/243.

**Comment by Fuco1** [comment]
Will be fixed with the release so I'll close this.
